# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c
script: ./travis-tool.sh run_tests

before_script:
  - sudo apt-get update
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh aptget_install gdal-bin libgdal1-dev libproj-dev
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_r rgdal
env:
   global:
     - R_LIBS="http://cran.rstudio.com"
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - BOOTSTRAP_LATEX=""
     - NOT_CRAN="true"

after_script:
  - "./travis-tool.sh dump_logs"


script: ./travis-tool.sh run_tests

notifications:
  email:
    on_success: change
    on_failure: change
