# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r
sudo: required

env:
   global:
     - R_LIBS="http://cran.rstudio.com"
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - BOOTSTRAP_LATEX=""
     - NOT_CRAN="true"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y gdal-bin libgdal-dev libgdal1-dev netcdf-bin libproj-dev libgdal1h
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_r rgdal

after_script:
  - "./travis-tool.sh dump_logs"

install:
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

notifications:
  email:
    on_success: change
    on_failure: change
